# Generated by Django 5.1.1 on 2024-09-12 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='showtimes',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='home.movie'),
        ),
        migrations.RemoveField(
            model_name='showtimes',
            name='show_date',
        ),
        migrations.RemoveField(
            model_name='showtimes',
            name='show_time',
        ),
        migrations.AlterField(
            model_name='showtimes',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater', to='home.theater'),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='show_date',
            field=models.ManyToManyField(to='home.date'),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='show_time',
            field=models.ManyToManyField(to='home.time'),
        ),
    ]
