# Generated by Django 5.1.1 on 2024-09-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_show_date_showtimes_show_dates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtimes',
            name='show_dates',
        ),
        migrations.RemoveField(
            model_name='showtimes',
            name='show_times',
        ),
        migrations.AddField(
            model_name='showtimes',
            name='show_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day', to='home.date'),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='show_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stime', to='home.time'),
        ),
    ]
