# Generated by Django 5.1.1 on 2024-09-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_showtimes_show_dates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='movie_posters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(max_length=50),
        ),
    ]
