# Generated by Django 5.1.1 on 2024-09-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_movie_banner_alter_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='tralier',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
