# Generated by Django 5.1.1 on 2024-09-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_movie_tralier'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total',
            field=models.CharField(default='100', max_length=20),
        ),
    ]
