# Generated by Django 5.1.1 on 2024-09-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_booking_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr',
            field=models.ImageField(null=True, upload_to='qrcode'),
        ),
    ]
