# Generated by Django 5.1.1 on 2024-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_booking_qr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='stars')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='star',
            field=models.ManyToManyField(to='home.star'),
        ),
    ]
