# Generated by Django 5.1.1 on 2024-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_star_movie_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='BID',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='BNO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='showtimes',
            name='screen',
            field=models.CharField(blank=True, default='AUDI 01', max_length=20, null=True),
        ),
    ]
