# Generated by Django 5.1.1 on 2024-10-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_booking_bid_booking_bno_showtimes_screen'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Typ', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='typ',
            field=models.ManyToManyField(to='home.typemov'),
        ),
    ]
