# Generated by Django 5.1.1 on 2024-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_typemov_movie_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='satus',
            field=models.BooleanField(default=True),
        ),
    ]
