# Generated by Django 5.1.1 on 2024-10-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_movie_satus'),
    ]

    operations = [
        migrations.AddField(
            model_name='showtimes',
            name='st',
            field=models.BooleanField(default=True),
        ),
    ]
